//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMMVWebPConverter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RMMVWebPConverter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should the conversion be:
        /// 1. Lossless (default, preserves a lot of detail but space savings are smaller)?
        /// 2. Lossy(smaller file size at the cost of image quality)?.
        /// </summary>
        internal static string ConversionModeQuestion {
            get {
                return ResourceManager.GetString("ConversionModeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location for the converter is set..
        /// </summary>
        internal static string ConverterLocationSet {
            get {
                return ResourceManager.GetString("ConverterLocationSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Where&apos;s the location of the cwebp?.
        /// </summary>
        internal static string CwebpApplLocationQuestion {
            get {
                return ResourceManager.GetString("CwebpApplLocationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where to put the converted images?.
        /// </summary>
        internal static string DestinationFolderLocationQuestion {
            get {
                return ResourceManager.GetString("DestinationFolderLocationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating folder...
        ///.
        /// </summary>
        internal static string FolderCreationMessage {
            get {
                return ResourceManager.GetString("FolderCreationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder does not exist..
        /// </summary>
        internal static string FolderDoesntExist {
            get {
                return ResourceManager.GetString("FolderDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished converting {0}..
        /// </summary>
        internal static string ImageConversionCompleteMessage {
            get {
                return ResourceManager.GetString("ImageConversionCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cwebp failed to compile {0}. It returned error code {1}..
        /// </summary>
        internal static string ImageConversionError {
            get {
                return ResourceManager.GetString("ImageConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting {0} to WebP....
        /// </summary>
        internal static string ImageConversionMessage {
            get {
                return ResourceManager.GetString("ImageConversionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like you gave a non-integer number. Applying the default setting..
        /// </summary>
        internal static string InvalidOptionMessage {
            get {
                return ResourceManager.GetString("InvalidOptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quality setting for the lossy conversion is set to {0}.
        /// </summary>
        internal static string LossyImageQualitySet {
            get {
                return ResourceManager.GetString("LossyImageQualitySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no cwebp in the folder..
        /// </summary>
        internal static string MissingcwebpApp {
            get {
                return ResourceManager.GetString("MissingcwebpApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert the path for cwebp.
        ///.
        /// </summary>
        internal static string NoCwebpAppLocationSet {
            get {
                return ResourceManager.GetString("NoCwebpAppLocationSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory isn&apos;t there. Please select an existing folder.
        ///.
        /// </summary>
        internal static string NoDirectoryFound {
            get {
                return ResourceManager.GetString("NoDirectoryFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the location of the folder.
        ///.
        /// </summary>
        internal static string NoFolderSpecified {
            get {
                return ResourceManager.GetString("NoFolderSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location for the output is set..
        /// </summary>
        internal static string OutputFolderSet {
            get {
                return ResourceManager.GetString("OutputFolderSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = Developed by AceOfAces..
        /// </summary>
        internal static string ProgramAuthor {
            get {
                return ResourceManager.GetString("ProgramAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = Licensed under the MIT license..
        /// </summary>
        internal static string ProgramLicense {
            get {
                return ResourceManager.GetString("ProgramLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = WebP Conversion and Preparation Tool for RPG Maker MV.
        /// </summary>
        internal static string ProgramTitle {
            get {
                return ResourceManager.GetString("ProgramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = Version R1.01 ({0}).
        /// </summary>
        internal static string ProgramVersion {
            get {
                return ResourceManager.GetString("ProgramVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Enter/Return to exit..
        /// </summary>
        internal static string PushEnterToExit {
            get {
                return ResourceManager.GetString("PushEnterToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Where are the files you want to convert to? .
        /// </summary>
        internal static string SourceFolderLocationQuestion {
            get {
                return ResourceManager.GetString("SourceFolderLocationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source location doesn&apos;t exist..
        /// </summary>
        internal static string SourceLocationDoesntExist {
            get {
                return ResourceManager.GetString("SourceLocationDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location for source is set..
        /// </summary>
        internal static string SourceLocationSet {
            get {
                return ResourceManager.GetString("SourceLocationSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ========================================================.
        /// </summary>
        internal static string SpliterText {
            get {
                return ResourceManager.GetString("SpliterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///The task was completed..
        /// </summary>
        internal static string TaskCompletedMessage {
            get {
                return ResourceManager.GetString("TaskCompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] .
        /// </summary>
        internal static string TimecodeFormatString {
            get {
                return ResourceManager.GetString("TimecodeFormatString", resourceCulture);
            }
        }
    }
}
